name: Deploy to GH pages

on: 
  push:
    branches:    
      - lesson-7
    paths-ignore:
      - 'public/**'
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: DEPLOY
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        SSH_DIR="${HOME}/.ssh"
        mkdir "${SSH_DIR}"
        ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
        echo "${ACTIONS_DEPLOY_KEY}" > "${SSH_DIR}/id_rsa"
        chmod 400 "${SSH_DIR}/id_rsa"
        
        git checkout lesson-7
        git remote -v
        git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
        git remote -v
        rm .gitignore
        git add public
        git commit -am "GitHub Action's build"
        git subtree split --prefix public -b gh-pages
        git push -f origin gh-pages:gh-pages

